### ISSUE TITLE
Filter not Wokring

### ISSUE THREAD

**Issue by tommyfinn** [RallyCommunity/PSITrackingApp#3] opened 2014-08-07 23:36 UTC
When i click on the filter it will not let me apply a filter like it does in the iteration tracker.(query)
![image](https://cloud.githubusercontent.com/assets/5825685/3850845/83996c64-1e8b-11e4-91d2-5c0fcaf97062.png)

![image](https://cloud.githubusercontent.com/assets/5825685/3850851/957ee472-1e8b-11e4-9e98-7d048d7542b2.png)

**Comment by krmorse** [comment] 2018-04-17 21:28
closing as dupe of #17

**Closed by krmorse** 2018-04-17 21:28 UTC
